const siteUrl = 'https://nbhoz.ru';

module.exports = {
  siteUrl,
  generateRobotsTxt: true,
  robotsTxtOptions: {
    policies: [
      {
        userAgent: '*',
        disallow: [
          '/admin',
          '/admin/*',
          '/checkout',
          '/checkout/*',
          '/cart',
          '/cart/*',
          '/profile',
          '/profile/*',
          '/orders',
          '/orders/*',
          '/wishlist',
          '/wishlist/*',
          '/after-payment',
          '/after-payment/*',
          '/rekvizity-ep-d',
          '/help',
          '/return-policy',
          '/how-to-buy',
          '/discount',
          '/guarantee',
          '/delivery',
          '/offerta',
          '/info-refund',
          '/user-agreement',
          '/privacy',
          '/api',
          '/api/*',
          '\nClean-param: ref /catalog',
        ],
        allow: ['/', '/*'],
      },
      // {
      //   userAgent: 'Yandex',
      //   disallow: '\nClean-param: ref /catalog',
      // },
    ],
    additionalSitemaps: [
      `${siteUrl}/server-sitemap.xml`,
      `${siteUrl}/sitemap.xml`,
    ],
  },
  exclude: [
    '/admin',
    '/admin/*',
    '/checkout',
    '/checkout/*',
    '/cart',
    '/cart/*',
    '/profile',
    '/profile/*',
    '/orders',
    '/orders/*',
    '/wishlist',
    '/wishlist/*',
    '/after-payment',
    '/after-payment/*',
    '/rekvizity-ep-d',
    '/help',
    '/api',
    '/api/*',
  ],
};
