const siteUrl = 'https://nbhoz.ru';

module.exports = {
  siteUrl,
  generateRobotsTxt: true,
  robotsTxtOptions: {
    policies: [
      {
        userAgent: '*',
        disallow: [
          '/admin',
          '/admin/*',
          '/checkout',
          '/checkout/*',
          '/cart',
          '/cart/*',
          '/profile',
          '/profile/*',
          '/orders',
          '/orders/*',
          '/wishlist',
          '/wishlist/*',
          '/after-payment',
          '/after-payment/*',
          '/rekvizity-ep-d',
          '/help',
          '/return-policy',
          '/how-to-buy',
          '/discount',
          '/guarantee',
          '/delivery',
          '/offerta',
          '/info-refund',
          '/user-agreement',
          '/privacy',
          '/api',
          '/api/*',
          '\nClean-param: categories&subCategories&tags&colors&minPrice&maxPrice&page&limit /catalog',
        ],
        allow: ['/', '/*'],
      },
      // {
      //   userAgent: 'Yandex',
      //   disallow: [
      //     '\nClean-param: categories&subCategories&tags&colors&minPrice&maxPrice /catalog',
      //     '/admin',
      //     '/admin/*',
      //     '/checkout',
      //     '/checkout/*',
      //     '/cart',
      //     '/cart/*',
      //     '/profile',
      //     '/profile/*',
      //     '/orders',
      //     '/orders/*',
      //     '/wishlist',
      //     '/wishlist/*',
      //     '/after-payment',
      //     '/after-payment/*',
      //     '/rekvizity-ep-d',
      //     '/help',
      //     '/return-policy',
      //     '/how-to-buy',
      //     '/discount',
      //     '/guarantee',
      //     '/delivery',
      //     '/offerta',
      //     '/info-refund',
      //     '/user-agreement',
      //     '/privacy',
      //     '/api',
      //     '/api/*',
      //   ],
      // },
    ],
    additionalSitemaps: [
      `${siteUrl}/server-sitemap.xml`,
      `${siteUrl}/sitemap.xml`,
    ],
  },
  exclude: [
    '/admin',
    '/admin/*',
    '/checkout',
    '/checkout/*',
    '/cart',
    '/cart/*',
    '/profile',
    '/profile/*',
    '/orders',
    '/orders/*',
    '/wishlist',
    '/wishlist/*',
    '/after-payment',
    '/after-payment/*',
    '/rekvizity-ep-d',
    '/help',
    '/api',
    '/api/*',
  ],
};
