const siteUrl = 'https://nbhoz.ru';

module.exports = {
  siteUrl,
  generateRobotsTxt: true,
  robotsTxtOptions: {
    policies: [
      {
        userAgent: '*',
        disallow: [
          '/admin',
          '/admin/*',
          '/checkout',
          '/checkout/*',
          '/cart',
          '/cart/*',
          '/profile',
          '/profile/*',
          '/orders',
          '/orders/*',
          '/wishlist',
          '/wishlist/*',
          '/reviews',
          '/help',
          '/dilevery',
          '/user-agreement',
          '/copyright-terms',
          '/return-policy',
          '/privacy',
          '/news',
          '/news/*',
          '/404',
          '/500',
          '\nClean-param: categories&subCategories&tags&colors&minPrice&maxPrice&page&limit /catalog',
        ],
        allow: ['/', '/*'],
      },
    ],
    additionalSitemaps: [
      `${siteUrl}/server-sitemap.xml`,
      `${siteUrl}/sitemap.xml`,
    ],
  },
  exclude: [
    '/admin',
    '/admin/*',
    '/checkout',
    '/checkout/*',
    '/cart',
    '/cart/*',
    '/profile',
    '/profile/*',
    '/orders',
    '/orders/*',
    '/wishlist',
    '/wishlist/*',
    '/help',
    '/dilevery',
    '/user-agreement',
    '/copyright-terms',
    '/return-policy',
    '/privacy',
    '/news',
    '/news/*',
    '/404',
    '/500',
    '\nClean-param: categories&subCategories&tags&colors&minPrice&maxPrice&page&limit /catalog',
  ],
};
