export enum ManageCheckoutFields {
  Variant = 'variant',
  ProductSize = 'productSize',
  Qty = 'qty',
  IsAddToCart = 'isAddToCart',
  CheckouType = 'checkoutType',
  UserEmail = 'userEmail',
  ReceiverName = 'receiverName',
  ReceiverPhone = 'receiverPhone',
  ReceiverEmail = 'receiverEmail',
  Address = 'address',
  RoomOrOffice = 'roomOrOffice',
  Door = 'door',
  Floor = 'floor',
  RignBell = 'rignBell',
  ZipCode = 'zipCode',
  PaymentMethod = 'paymentMethod',
}
